name: Deploy Project
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        id: tests
        continue-on-error: true
        run: npm run test
      - name: Check Steps Context
        run: |
          echo 'Steps Context: ${{ toJSON(steps) }}'
      - name: Outpot Test Reports
        run: |
          echo "JSON Reports"
          cat reports/report.json

          echo "XML Reports"
          cat reports/report.xml
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Zip application built code (dist folder)
        run: |
          cd dist
          zip ../build.zip * -r
      - name: Store zipped built code in artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.zip
          retention-days: 1

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: needs.test.result == 'success'
    steps:
      - name: Install NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Download adtifact with zipped built application code
        uses: actions/download-artifact@v3
        with:
          path: build.zip
          name: build
      - name: Unzip built application code
        run: |
          ls -la
          unzip ./build.zip
          rm build.zip
      - name: Deploy Project
        run: ls -R
