name: repository_dispatch
on:
  repository_dispatch:
    types:
      - test
      - demo
      - local
      - REST

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Context
        run: |
          echo "${{ toJSON(github) }}"
