name: Test Project
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        continue-on-error: true
        run: npm run test
      - name: Check Steps Context
        run: |
          echo 'Steps Context: ${{ toJSON(steps) }}'
      - name: Outpot Test Reports
        run: |
          echo "JSON Reports"
          cat reports/report.json

          echo "XML Reports"
          cat reports/report.xml
